tiktok_insight/insight_app/urls.py
from insight_app import views
from django.urls import path

urlpatterns = [
    path("", views.home, name="home"),
    path("upload-csv/", views.upload_csv, name="upload_csv"),
    path("analysis/", views.analysis, name="analysis"),
]

tiktok_insight/tiktok_insight/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("insight_app.urls")),
]

tiktok_insight/insight_app/models.py
from django.db import models
from datetime import datetime
from loguru import logger
from csv import reader
import pandas as pd
import pycountry
import numpy as np

# generator chain
from itertools import chain


class TotalByDay(models.Model):
    date = models.DateField(primary_key=True)
    video_views = models.IntegerField()
    profile_views = models.IntegerField()
    likes = models.IntegerField()
    comments = models.IntegerField()
    shares = models.IntegerField()
    unique_viewers = models.IntegerField()
    report = models.ForeignKey("Report", on_delete=models.CASCADE)

    @classmethod
    def from_csv(cls, row, report):
        (
            date_str,
            video_views,
            profile_views,
            likes,
            comments,
            shares,
            unique_viewers,
        ) = row
        date = datetime.strptime(date_str, "%Y-%m-%d").date()
        return cls(
            date=date,
            video_views=int(video_views),
            profile_views=int(profile_views),
            likes=int(likes),
            comments=int(comments),
            shares=int(shares),
            unique_viewers=int(unique_viewers),
            report=report,
        )

    def __str__(self):
        return f"{self.date} views: {self.video_views}"


class Video(models.Model):
    time = models.DateTimeField()
    video_title = models.CharField(max_length=255)
    video_link = models.URLField(max_length=500)
    post_time = models.DateTimeField(primary_key=True)
    video_views_within_7_days = models.IntegerField()
    total_likes = models.IntegerField()
    total_comments = models.IntegerField()
    total_shares = models.IntegerField()
    total_views = models.IntegerField()
    tags = models.TextField()
    report = models.ForeignKey("Report", on_delete=models.CASCADE)

    @classmethod
    def from_csv(cls, row, report):
        row = row.tolist()
        if len(row) == 8:
            row.insert(4, 0)
        if len(row) != 9:
            raise ValueError(f"Row has {len(row)} columns, expected 9: {row}")
        (
            time_str,
            video_title,
            video_link,
            post_time_str,
            video_views_within_7_days,
            total_likes,
            total_comments,
            total_shares,
            total_views,
        ) = row
        logger.info(f"Creating video from {row}")
        time = datetime.strptime(time_str, "%Y-%m-%d %H:%M")
        post_time = datetime.strptime(post_time_str, "%Y-%m-%d %H:%M")
        tags = " ".join(tag.strip() for tag in video_title.split("#")[1:])
        title = video_title.split("#")[0].strip()
        if cls.objects.filter(post_time=post_time, report=report).exists():
            logger.warning(f"Video with post_time {post_time} already exists")
            obj = cls.objects.get(post_time=post_time, report=report)
            if video_views_within_7_days > 0:
                obj.video_views_within_7_days = video_views_within_7_days
            return obj
        try:
            total_views = int(total_views)
        except ValueError:
            logger.warning(f"Total views {total_views} is not a number")
            total_views = 0

        return cls(
            time=time,
            video_title=title,
            video_link=video_link,
            post_time=post_time,
            total_likes=int(total_likes),
            video_views_within_7_days=int(video_views_within_7_days),
            total_comments=int(total_comments),
            total_shares=int(total_shares),
            total_views=total_views,
            tags=tags,
            report=report,
        )

    def __str__(self):
        return f"{self.video_title} - {self.post_time} ({self.total_views})"

    @property
    def likes_to_views_ratio(self):
        return self.total_likes * 100 / self.total_views

    @property
    def comments_to_views_ratio(self):
        return self.total_comments * 100 / self.total_views

    @property
    def shares_to_views_ratio(self):
        return self.total_shares * 100 / self.total_views


class Report(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    @property
    def total_views(self):
        return sum([entry.video_views for entry in self.totalbyday_set.all()])

    @property
    def total_likes(self):
        return sum([entry.likes for entry in self.totalbyday_set.all()])

    @property
    def total_comments(self):
        return sum([entry.comments for entry in self.totalbyday_set.all()])

    @property
    def total_shares(self):
        return sum([entry.shares for entry in self.totalbyday_set.all()])

    @property
    def total_unique_viewers(self):
        return sum([entry.unique_viewers for entry in self.totalbyday_set.all()])

    @property
    def avg_likes_to_view_ratios(self):
        return np.mean([video.likes_to_views_ratio for video in self.video_set.all()])

    @property
    def total_videos(self):
        return self.video_set.count()

    @property
    def total_territories(self):
        return self.territory_set.count()

    @property
    def most_popular_country(self):
        terr = self.territory_set.all()
        return max(terr, key=lambda x: x.distribution)

    @classmethod
    def from_csvs(
        cls,
        total: pd.DataFrame,
        trending: pd.DataFrame,
        videos: pd.DataFrame,
        gender: pd.DataFrame,
        territory: pd.DataFrame,
        followers: pd.DataFrame,
        activity: pd.DataFrame,
        title: str,
        description: str,
    ):
        report = cls.objects.create(title=title, description=description)

        def create_instances(df, model):
            for _, row in df.iterrows():
                instance = model.from_csv(row, report)
                instance.save()

        create_instances(total, TotalByDay)
        create_instances(videos, Video)
        create_instances(trending, Video)
        print(pd.concat([videos, trending]))
        create_instances(gender, GenderDistribution)
        create_instances(territory, Territory)
        create_instances(followers, TotalFollowers)
        create_instances(activity, FollowersActivity)

        return report

    def __str__(self):
        return self.title


class Territory(models.Model):
    country = models.CharField(max_length=100, help_text="Full Country name")
    distribution = models.FloatField()
    report = models.ForeignKey("Report", on_delete=models.CASCADE)

    @classmethod
    def from_csv(cls, row, report):
        country_code = row[0]

        country_name = pycountry.countries.get(alpha_2=country_code).name
        distribution = row[1]
        distribution = float(distribution.strip("%")) / 100
        return cls.objects.create(
            country=country_name, distribution=distribution, report=report
        )

    def __str__(self):
        return f"{self.country} distribution: {self.distribution}"


class TotalFollowers(models.Model):
    date = models.DateField(primary_key=True)
    followers = models.IntegerField(null=True, blank=True)
    difference = models.IntegerField(null=True, blank=True)
    report = models.ForeignKey("Report", on_delete=models.CASCADE)

    @classmethod
    def from_csv(cls, row, report):
        date_str, followers, difference = row
        date = datetime.strptime(date_str, "%Y-%m-%d %H:%M")
        try:
            followers = int(followers)
        except (ValueError, TypeError):
            followers = 0

        try:
            difference = int(difference)
        except (ValueError, TypeError):
            difference = 0
        return cls(date=date, followers=followers, difference=difference, report=report)

    def __str__(self):
        return f"{self.date} followers: {self.followers}"


class GenderDistribution(models.Model):
    gender = models.CharField(max_length=20)
    distribution = models.FloatField()
    report = models.ForeignKey("Report", on_delete=models.CASCADE)

    @classmethod
    def from_csv(cls, row, report):
        gender, distribution = row
        distribution = float(distribution.strip("%")) / 100
        return cls(gender=gender, distribution=distribution, report=report)

    def __str__(self):
        return f"{self.gender} distribution: {self.distribution}"


class FollowersActivity(models.Model):
    date = models.DateField()
    hour = models.IntegerField()
    active_followers = models.IntegerField()
    report = models.ForeignKey("Report", on_delete=models.CASCADE)

    @classmethod
    def from_csv(cls, row, report):
        date_str, hour, active_followers = row
        date = datetime.strptime(date_str, "%Y-%m-%d").date()
        hour = int(hour)
        active_followers = int(active_followers)
        return cls(
            date=date, hour=hour, active_followers=active_followers, report=report
        )

    def __str__(self):
        return (
            f"{self.date} hour: {self.hour} active followers: {self.active_followers}"
        )

tiktok_insight/insight_app/views.py
from django.shortcuts import render
from loguru import logger
import csv
from django.http import HttpResponse
from .models import TotalByDay, Video, Report
from django.shortcuts import redirect
from insight_app.libs.plot_data import Plotter
import pandas as pd


def upload_csv(request):
    if request.method == "POST":
        files = [
            request.FILES["videos"],
            request.FILES["trending"],
            request.FILES["total"],
            request.FILES["gender"],
            request.FILES["followers"],
            request.FILES["territory"],
            request.FILES["activity"],
        ]

        dataframes = [pd.read_csv(file) for file in files]
        # add insert column (on 4 index) to the videos video_views_within_7_days = 0
        report = Report.from_csvs(
            videos=dataframes[0],
            trending=dataframes[1],
            total=dataframes[2],
            gender=dataframes[3],
            followers=dataframes[4],
            territory=dataframes[5],
            activity=dataframes[6],
            title=request.POST["title"],
            description=request.POST["description"],
        )
        report.save()

        return redirect("analysis")

    return render(request, "home.html")


# Create your views here.
def home(request):
    return render(request, "home.html")


def analysis(request):
    report = Report.objects.last()
    plotter = Plotter(report)
    plots = plotter()
    return render(request, "analysis.html", {"plot_data": plots, "report": report})

tiktok_insight/insight_app/templates/_video_stats.html
{% load filters %}
<div class="card m-2  clickable-card ">
    <div class="card-header border-1 p-3 m-0 d-flex justify-content-between {% if video.total_views > 100000 %}bg-success{% endif %}">
        <a class="fs-5 text-lead text-decoration-none text-light"
           href="{{ video.video_link }}">{{ video.video_title|truncatechars:45 }}</a>
        <span>{{ video.post_time }}</span>
    </div>
    <div class="card-body ">
        <div class="row my-2">
            <div class="col-3 fs-4 text-center">
                <i class="text-primary fa-solid fa-eye"></i> {{ video.total_views|format_number }}
            </div>
            <div class="col-3 fs-4 text-center">
                <i class="fas fa-heart text-danger"></i> {{ video.total_likes|format_number }}
            </div>
            <div class="col-3 fs-4 text-center">
                <i class="fas fa-comments text-warning"></i>  {{ video.total_comments|format_number }}
            </div>
            <div class="col-3 fs-4 text-center">
                <i class="fas fa-share text-success"></i>  {{ video.total_shares|format_number }}
            </div>
        </div>
        <div class="row my-2">
            <div class="col-3 fs-4 text-center"></div>
            <div class="col-3 fs-4 text-center">
                {{ video.likes_to_views_ratio|floatformat:2 }}
                <i class="fa-solid fa-percent"></i>
            </div>
            <div class="col-3 fs-4 text-center">
                {{ video.comments_to_views_ratio|floatformat:2 }}
                <i class="fas fa-percent"></i>
            </div>
            <div class="col-3 fs-4 text-center">
                {{ video.shares_to_views_ratio|floatformat:2 }}
                <i class="fas fa-percent"></i>
            </div>
        </div>
    </div>
    <div class="card-footer text-muted">Tags: {{ video.tags }}</div>
</div>

tiktok_insight/insight_app/templates/analysis.html
{% extends "base.html" %}
{% load static %}
{% block extra_head %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
    <script src="{% static 'js/plot_total_by_day.js' %}" defer></script>
    <script src="{% static 'js/plot_genders_distribution.js' %}" defer></script>
    <script src="{% static 'js/plot_followers.js' %}" defer></script>
    <script src="{% static 'js/plot_activity.js' %}" defer></script>
    <script src="{% static 'js/plot_region.js' %}" defer type="module"></script>
{% endblock %}
{% block content %}
    {% load filters %}
    <div class="container container-fluid my-4 p-1">
        <h1 class="display-5">
            Results for: <em>{{ report.title|truncatechars:40 }}</em>
        </h1>
        <hr class="my-5" />
        <div class="row">
            <div class="mb-4 col-lg-4 col-12">
                <div class="border rounded m-3 mx-1 p-1 clickable-card shadow">
                    <h1 class="display-4  lead text-center p-2">
                        <p class="fs-2">Total views</p>
                        {{ report.total_views|format_number }}<i class="px-3 text-primary  fa-regular fa-eye"></i>
                    </h1>
                </div>
                <div class="border rounded m-3 mx-1 p-1 clickable-card shadow">
                    <h1 class="display-4  lead text-center p-2">
                        <p class="fs-2">Videos</p>
                        {{ report.total_videos|format_number }}<i class="px-3 text-warning  fa-regular fa-video"></i>
                    </h1>
                </div>
                <div class="border rounded m-3 mx-1 p-1 clickable-card shadow">
                    <h1 class="display-4  lead text-center p-2">
                        <p class="fs-2">Likes</p>
                        {{ report.total_likes|format_number }}<i class="px-3 text-danger fas fa-heart"></i>
                    </h1>
                </div>
            </div>
            <div class="mb-4 col-lg-8 col-12">
                <canvas id="totalByDay" data-plot="{{ plot_data.total_by_day }}"></canvas>
            </div>
            <h1 class="display-5 text-warning">followers</h1>
            <hr class="my-5">
            <div class="mb-4 col-lg-8 col-12">
                <canvas id="followers" data-plot="{{ plot_data.followers }}"></canvas>
            </div>
            <div class="mb-4 col-lg-4 col-12">
                <div class="border rounded m-3 mx-1 p-1 clickable-card shadow">
                    <h1 class="display-4  lead text-center p-2">
                        <p class="fs-2">Observers</p>
                        {{ report.totalfollowers_set.last.followers|format_number }}<i class="px-3 text-primary  fa-regular fa-person"></i>
                    </h1>
                </div>
                <div class="border rounded m-3 mx-1 p-1 clickable-card shadow">
                    <h1 class="display-4  lead text-center p-2">
                        <p class="fs-2">Unique viewers</p>
                        {{ report.total_unique_viewers|format_number }}
                    </h1>
                </div>
                <div class="border rounded m-3 mx-1 p-12 clickable-card shadow">
                    <h1 class="display-4  lead text-center p-2">
                        <p class="fs-2">Countries</p>
                        {{ report.total_territories }} <i class="fa-solid fa-globe text-success"></i>
                    </h1>
                </div>
            </div>
            <hr class="my-5">
            <div class="mb-4 col-lg-4 col-12">
                <canvas id="gendersDistribution" data-plot="{{ plot_data.genders }}"></canvas>
            </div>
            <div class="mb-4 col-lg-8 col-12">
                <canvas id="regions" data-plot="{{ plot_data.regions }}"></canvas>
            </div>
            <h1 class="display-5 text-warning">Tips</h1>
            <hr class="my-5">
            <div class="mb-4 col-lg-8 col-12">
                <canvas id="activity" data-plot="{{ plot_data.followers_activity_by_hour }}"></canvas>
            </div>
            <div class="mb-4 col-lg-4 col-12">
                <div class="border rounded m-3 mx-1 p-1 clickable-card shadow">
                    <h1 class="display-4  lead text-center p-2">
                        <p class="fs-2">Best hour to upload video</p>
                        {{ plot_data.best_upload_hour }}<i class="px-3 text-warning  fa-regular fa-stopwatch"></i>
                    </h1>
                </div>
                <div class="border rounded m-3 mx-1 p-1 clickable-card shadow">
                    <h1 class="display-4  lead text-center p-2">
                        <p class="fs-2">Make vids for people from</p>
                        {{ report.most_popular_country.country }}<i class="px-3 text-warning  fa-regular fa-flag"></i>
                    </h1>
                </div>
            </div>
            <h1 class="display-5 text-warning">Videos</h1>
            <hr class="my-5">
            {% for video in report.video_set.all %}
                <div class="col-lg-6 col-12 mb-4 p-1">{% include "_video_stats.html" with video=video %}</div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

tiktok_insight/insight_app/templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
      <head>
            <meta name="description" content="Tiktok insight" />
            {% load static %}
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Tiktok insight</title>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
                    crossorigin="anonymous"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
            {% comment %} <script type="text/javascript"  src="{% static 'js/mdb.min.js' %}"></script> {% endcomment %}
            {% block extra_head %}
            {% endblock extra_head %}
            <link href="{% static 'fontawesomefree/css/fontawesome.css' %}"
                  rel="stylesheet"
                  type="text/css" />
            <link href="{% static 'fontawesomefree/css/brands.css' %}"
                  rel="stylesheet"
                  type="text/css" />
            <link href="{% static 'fontawesomefree/css/solid.css' %}"
                  rel="stylesheet"
                  type="text/css" />
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
            <link rel="stylesheet" href="{% static 'css/style.css' %}" />
            <script src="{% static 'js/script.js' %}"></script>
            <link rel="shortcut icon"
                  type="image/png"
                  href="{% static 'img/favicon.ico' %}">
            <!-- <script src="{% static 'js/bootstrap.min.js' %}" defer></script> -->
      </head>
      <body class="d-flex flex-column h-100 w-100 ">
            {% include "navbar.html" %}
            <main class="h-100 m-0">
                  {% block content %}
                  {% endblock content %}
            </main>
            <footer class="mt-5 rounded border footer">
                  <div class="text-center p-3">
                        © 2024 Copyright:
                        <a class="text-danger"
                           href="https://github.com/michalskibinski109/chess-stats">Michal Skibinski</a>
                  </div>
            </footer>
      </body>
</html>

tiktok_insight/insight_app/templates/home.html
{% extends "base.html" %}
{% block content %}
  <div class="alert alert-info" role="alert" hidden>
    <p>Upload 3 CSV files to compare them.</p>
    <p>Each file should have the same columns and the same order of columns.</p>
  </div>
  <div class="container container-fluid p-5">
    <h1 class="display-4">Upload CSV Files</h1>
    <hr class="mt-5" />
    <form method="post"
          enctype="multipart/form-data"
          action="{% url 'upload_csv' %}">
      {% csrf_token %}
      <div class="mb-3">
        <label for="title" class="form-label fs-5">Title</label>
        <input type="text"
               class="form-control"
               id="title"
               name="title"
               value="My tiktok performance">
      </div>
      <div class="mb-3">
        <label for="description" class="form-label fs-5">Description</label>
        <textarea class="form-control" id="description" name="description" rows="3">Created by tiktok insight</textarea>
      </div>
      <div class="mb-3">
        <label for="videos" class="form-label fs-5">Video posts.csv</label>
        <input type="file"
               class="form-control"
               id="videos"
               name="videos"
               accept=".csv">
      </div>
      <div class="mb-3">
        <label for="trending" class="form-label fs-5">Trending videos.csv</label>
        <input type="file"
               class="form-control"
               id="trending"
               name="trending"
               accept=".csv">
      </div>
      <div class="mb-3">
        <label for="total" class="form-label fs-5">Last xx days.cvs</label>
        <input type="file"
               class="form-control"
               id="total"
               name="total"
               accept=".csv">
      </div>
      <div class="mb-3">
        <label for="gender" class="form-label fs-5">Gender.csv</label>
        <input type="file"
               class="form-control"
               id="gender"
               name="gender"
               accept=".csv">
      </div>
      <div class="mb-3">
        <label for="followers" class="form-label fs-5">Total Followers.csv</label>
        <input type="file"
               class="form-control"
               id="followers"
               name="followers"
               accept=".csv">
      </div>
      <div class="mb-3">
        <label for="territory" class="form-label fs-5">Top Territories.csv</label>
        <input type="file"
               class="form-control"
               id="territory"
               name="territory"
               accept=".csv">
      </div>
      <div class="mb-3">
        <label for="activity" class="form-label fs-5">Follower activity.csv</label>
        <input type="file"
               class="form-control"
               id="activity"
               name="activity"
               accept=".csv">
      </div>
      <button type="submit" class="btn btn-primary">Upload</button>
    </form>
  </div>
{% endblock %}

tiktok_insight/insight_app/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg rounded-bottom border-3 border-bottom border-danger pb-1">
    <div class="container-fluid">
        <a class="navbar-brand nav-item d-flex justify-content-center align-items-center"
           href="/"
           style="height: 100%">
            <img src="{% static 'img/logo.png' %}"
                 alt="logo"
                 width="40"
                 height="40"
                 class="d-inline-block align-middle rounded">
            <p class="fs-4 mx-1 m-0 text-center">Tiktok insiht</p>
        </a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active text-start " aria-current="page" href="/admin">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active text-start "
                       aria-current="page"
                       href="{% url 'analysis' %}">Analysis</a>
                </li>
            </ul>
        </div>
    </div>
</nav>